### ISSUE TITLE
The update method of requirement creates a new item but not update an old one

### ISSUE THREAD

**Issue by TargaryenQi** [watermelonfarmers/watermelon#9]
The old update method used the requirementToRequirementEntityMapper, which does not set the id of requirementEntity, so when saving the requirementEntity, a new one will be created in the database.

Then I fix this by first search requirementEntity by the id of the requirement and then update the information of the requirement to the requirementEntity. So the requirementEntity has the original ID and when save it uses requirement repository, the repository will update the old one with the new one.

But, what is wired is that this works in the server, but not on the front side. And  Jesse and I are working on this.

**Comment by TargaryenQi** [comment]
@bingemi When you are convenient, please help us out

**Comment by bingemi** [comment]
code works as expected, the build is not deploying because the following unit tests did not pass

com.watermelonfarmers.watermelon.processors.RequirementProcessorTest > whenUpdateRequirementIsCalledAndPrincipalRequirementIsNullUnauthorizedIsReturned FAILED
    org.junit.ComparisonFailure at RequirementProcessorTest.java:87

com.watermelonfarmers.watermelon.processors.RequirementProcessorTest > whenCreateRequirementIsCalledAndRequirementIdAlreadyExistsResponseMessageIsAlreadyExists FAILED
    org.springframework.dao.DataIntegrityViolationException

com.watermelonfarmers.watermelon.processors.RequirementProcessorTest > whenCreateRequirementIsCalledAndRequirementIdAlreadyExistsResponseStatusCodeIsConflict FAILED
    org.springframework.dao.DataIntegrityViolationException

**Comment by TargaryenQi** [comment]
So maybe if I delete these test, for now, the build will deploy successfully @bingemi
